### ISSUE TITLE
ux425ja wrong reaction on some buttons

### ISSUE THREAD

**Issue by denesco** [mohamed-badaoui/asus-touchpad-numpad-driver#120]
First of all - Thank you very much! NumberPad held me down from leaving windows for good, on this laptop. 
The problem is the following - some "keys" have wrong binding. (.)=>(0) , (enter)=>(.) , (%)=>(=) . 

the log from terminal

`apt is here
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libevdev2 is already the newest version (1.12.1+dfsg-1).
i2c-tools is already the newest version (4.3-2build1).
python3-libevdev is already the newest version (0.5-3).
git is already the newest version (1:2.34.1-1ubuntu1.11).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Testing interface i2c-0 : failed
Testing interface i2c-1 : sucess

Select models keypad layout:
1) gx701.py
2) m433ia.py
3) ux433fa.py
4) ux581l.py
5) Quit
Please enter your choice 3

What is your keyboard layout?
1) Qwerty
2) Azerty
3) Quit
Please enter your choice [1-3]: 1
Add asus touchpad service in /etc/systemd/system/
Created symlink /etc/systemd/system/default.target.wants/asus_touchpad_numpad.service → /etc/systemd/system/asus_touchpad_numpad.service.
Asus touchpad service enabled
Asus touchpad service started
`

**Comment by mohamed-badaoui** [comment]
The ux433fa and ux425ja laptops do not have the same keyboard.
  Feel free to add a PR to add your laptop configuration
