### ISSUE TITLE
consider changing the name?

### ISSUE THREAD

**Issue by adlererik** [mohamed-badaoui/asus-touchpad-numpad-driver#17]
Might want to consider changing the name to something like asus-zenbook-touchpad-numberpad. This "driver" works on a lot of models.
btw thx for the merge.

**Comment by mohamed-badaoui** [comment]
You are right.
Repository renamed 
https://github.com/mohamed-badaoui/asus-touchpad-numpad-driver

Ps: this driver works also for vivobook models, not only Zenbook

**Comment by mohamed-badaoui** [comment]
Thanks for you contributions.
