### ISSUE TITLE
asus vivobook s14 m443ia numpad backlight does not work

### ISSUE THREAD

**Issue by dark0ghost** [mohamed-badaoui/asus-touchpad-numpad-driver#20]
The keyboard itself works for me, but it lacks character highlighting.

**Comment by mohamed-badaoui** [comment]
It has been tested on this model and worked.
Your issue is probably due to system configuration or installation.
Please use launchpad thread, if you need support for this:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1810183
