### ISSUE TITLE
ASUS M433IA

### ISSUE THREAD

**Issue by magellan-13016** [mohamed-badaoui/asus-touchpad-numpad-driver#23]
Hello Mohamed,

After many updates were deployed on my Linux Mint system, I wanted to retest the driver for the Numpad on my ASUS M433IA.

Unfortunately, the driver doesn't work at all, whereas during the previous developments, it worked.

For the record, I have an AZERTY keyboard with % and = symbols and the instructions to turn my numpad on and off are : 

ON: sudo i2ctransfer -f -y 0 w13@0x15 0x05 0x00 0x3d 0x03 0x06 0x00 0x07 0x00 0x0d 0x14 0x03 0x01 0xad

OFF: sudo i2ctransfer -f -y 0 w13@0x15 0x05 0x00 0x3d 0x03 0x06 0x00 0x07 0x00 0x0d 0x14 0x03 0x00 0xad

I have reinstalled the old version I had but as soon as the Firefox browser is launched, the keyboard freaks out as usual So I would like to test the latest version which seems to work for everyone but me.

Next holiday I'm going to install the latest version of Linux Mint on my computer and hopefully things will be better. But in the meantime, I'd like to be able to test the latest version of the driver.

Thanks in advance for your help.

David.

**Comment by mohamed-badaoui** [comment]
Hi David,

Did you try to follow the installation recommendations of the user Logix given on launchpad:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1810183

He wrote a post at:
https://www.linuxuprising.com/2021/05/how-to-get-numpad-embedded-into.html?m=1

I updated the README to avoid using Python PIP for the installation.
