### ISSUE TITLE
Enhancement: possibility not to use F8

### ISSUE THREAD

**Issue by nicosensei** [mohamed-badaoui/asus-touchpad-numpad-driver#27]
Hi,

I've installed the driver on my Asus UX425EA. It works pretty well and I can activate and deactivate the numeric pad using the touchpad upper right corner. However I'd like not to use F8, because it is a key I use very often in my code editor (next debugger step!), so I get a lot of flashing light ;-)

**Comment by mohamed-badaoui** [comment]
You made my day :-)

If you want to disable F8, you just need to comment out these lines:
https://github.com/mohamed-badaoui/asus-touchpad-numpad-driver/blob/main/touchpad_numpad_nosymbols.py#L138-L144

**Comment by mohamed-badaoui** [comment]
Duplicate 
https://github.com/mohamed-badaoui/asus-touchpad-numpad-driver/issues/7
