### ISSUE TITLE
This driver worked but I can't see any light.

### ISSUE THREAD

**Issue by batouei** [mohamed-badaoui/asus-touchpad-numpad-driver#29]
I have zenbook ux425ea, Numpad worked by this drivers but I can't see any light.
I also try to this:
`sudo i2ctransfer -f -y 0 w13@0x15 0x05 0x00 0x3d 0x03 0x06 0x00 0x07 0x00 0x0d 0x14 0x03 0x01 0xad
 ` but not worked.

**Comment by Gregoire-perso** [comment]
What say `sudo i2cdetect -l` ?

**Comment by mohamed-badaoui** [comment]
Check out and try the last version.
