### ISSUE TITLE
How do you found the command to light up the numpad ?

### ISSUE THREAD

**Issue by Gregoire-perso** [mohamed-badaoui/asus-touchpad-numpad-driver#32]
Hi @mohamed-badaoui !
Your driver is useful for me, and i was waiting for someone to do that, but i was interested in how do you found the i2c command used to light up the touchpad ? (this one for me : `sudo i2ctransfer -f -y 0 w13@0x15 0x05 0x00 0x3d 0x03 0x06 0x00 0x07 0x00 0x0d 0x14 0x03 0x01 0xad`)

And also, what means lines `Conflicts=getty@tty1.service` and `StandardInput=tty-force` in your .service file ?
(Actually, it doesn't work on my laptop if i ddon't remove the line `Conflicts=getty@tty1.service` )

**Comment by mohamed-badaoui** [comment]
Actually these command was found by a contributor on launchpad.

For the details, Have a look at: 
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1810183

Thanks for your nice contribution!
