### ISSUE TITLE
Service isn't enabled upon startup on Manjaro Distro

### ISSUE THREAD

**Issue by mozzribo** [mohamed-badaoui/asus-touchpad-numpad-driver#49]
Hi! Upon restart, the service is not running. I followed all the instructions You provided. Is there something I'm missing? Or is there some other issue? Running Manjaro.

**Comment by kawaegle** [comment]
I work on I have manjaro too

**Comment by kawaegle** [comment]
@mozzribo Can you show me the output of ```shell systemctl status asus_touchpad_numpad.service``` and ```shell systemctl status display_manager.service```

and also tell me witch DE (desktop environment you use)
