### ISSUE TITLE
TouchPad not highlited (ZenBook UX425EA_UX425EA)

### ISSUE THREAD

**Issue by AntonSh23** [mohamed-badaoui/asus-touchpad-numpad-driver#59]
Hi, i have next laptop
![image](https://user-images.githubusercontent.com/14983579/129785196-7ee18220-1a72-41ec-a22b-0a3c52620de7.png)

tried all installation options but i have next issue:
Numpad not highlighted(it just dark like turned off), but if i press right top corner i can write numbers like numpad is working properly.
Can you please direct me where i can find part of code which response for highlight of touch bar?
Tried to find by myself but with no result.
![image](https://user-images.githubusercontent.com/14983579/129785921-2a96de12-c407-4928-be7d-9bfe50b38471.png)

**Comment by kawaegle** [comment]
hello,

Can you show me the output of 

```sh
i2c-detect -l
```

```sh
uname -a
```

```sh
sudo systemctl status asus_touchpad_numpad.service
```

thx

**Comment by AntonSh23** [comment]
Hi @kawaegle , thx a lot for reply.
i2cdetect -l
![image](https://user-images.githubusercontent.com/14983579/131954987-00e59c29-ed20-48ea-96d4-040bddf1358e.png)
uname -a
![image](https://user-images.githubusercontent.com/14983579/131955054-a0887f4e-860c-414d-a8bb-442645814bac.png)
sudo systemctl status asus_touchpad_numpad.service
![image](https://user-images.githubusercontent.com/14983579/131955151-24ff23db-21a7-4c10-8bc8-f7da04103bd2.png)

**Comment by kawaegle** [comment]
can you try to install my fork I improved the file for this computer (because it's also mine) maybe it's with the i2c command the computer don't understand what to light up

https://github.com/oppaiweeb/asus-touchpad-numpad-driver

I wait for my PR to be accepted

**Comment by mohamed-badaoui** [comment]
Hi,

You should try it first manually.
It seems in your case that the right interface is number 2
```
i2c-2	unknown       	Synopsys DesignWare I2C adapter 	I2C adapter
```

So you could try to activate your numpad with
```
sudo i2ctransfer -f -y 2 w13@0x15 0x05 0x00 0x3d 0x03 0x06 0x00 0x07 0x00 0x0d 0x14 0x03 0x01 0xad
```

For information, PR has been accepted (Thanks Kawaegle) 
If manually command works, you should uninstall first and refresh your local repository (git pull) before reinstalling

**Comment by mohamed-badaoui** [comment]
Generally when the touchpad stay unlighted, it s mainly because i2c interface is not started.
Please check that when you run it manually, i2c interface has been well started.
So before running the script, start i2c interfaces and check it is running.

```
sudo modprobe i2c-dev
sudo i2cdetect -l
```

**Comment by arturf** [comment]
Guys just for fun. Some models from UX425EA series don't have Numpad. But driver works fine even without highlight. 
Probably all models have the similar hardware but Asus decided to make some economy on led lights :)
This is my case with a new laptop. Will change it and try again...
