### ISSUE TITLE
Multi-touch is not supported

### ISSUE THREAD

**Issue by HosseyNJF** [mohamed-badaoui/asus-touchpad-numpad-driver#69]
If one types fast and presses another number key while still holding the previous key, the second keystroke would simply get ignored. But In order to make typing fast possible, the keystrokes must still be recorded, just like a physical keyboard.

**Comment by ldrahnik** [comment]
You can test multi tap support up to quint tap here: https://github.com/ldrahnik/asus-touchpad-numpad-driver
