### ISSUE TITLE
It would be nice to disable keyboard support

### ISSUE THREAD

**Issue by angryziber** [mohamed-badaoui/asus-touchpad-numpad-driver#7]
Hijacking F8 is not a good thing - there's lots of use for F8 in many apps.
It would be nice to chose during install.sh whether to enable or disable keyboard key support

**Comment by mohamed-badaoui** [comment]
I agree. I think that it was a bad idea and think about to remove activation through the F8 keystroke

**Comment by kawaegle** [comment]
@mohamed-badaoui I'm working on it and on the X/Y position because it's sometime difficult to toggle

**Comment by mohamed-badaoui** [comment]
Disable F8 done.
