### ISSUE TITLE
Not detected here on NixOS with UX433

### ISSUE THREAD

**Issue by doronbehar** [mohamed-badaoui/asus-touchpad-numpad-driver#72]
I noticed you look into `/proc/bus/input/devices` [here](https://github.com/mohamed-badaoui/asus-touchpad-numpad-driver/blob/f9bd0400ce25d4a9eba30a342f647a560bb69984/asus_touchpad.py#L49-L50). What does it mean if the code doesn't find it? I noticed ux433 is supposed to be supported. The only device I can find there myself with the words ASUS is:

```
I: Bus=0019 Vendor=0000 Product=0000 Version=0000
N: Name="Asus WMI hotkeys"
P: Phys=asus-nb-wmi/input0
B: EV=100013
B: KEY=1000000080000 0 0 0 0 181606f00900000 8280027801701000 e000000000000 0
B: MSC=10
```

But that seems like something that controls the backlight according to: http://manpages.ubuntu.com/manpages/bionic/man4/acpi_asus_wmi.4freebsd.html . Perhaps I'm missing some kernel drivers?

I wish to add this program as a service for NixOS, thanks for any help.

**Comment by mohamed-badaoui** [comment]
Sorry but i do not have this OS linux to reproduce your issue.

**Comment by doronbehar** [comment]
It works for me now!
