### ISSUE TITLE
Enhancement request: map the "calculator symbol", left top of touchscreen to a F-key

### ISSUE THREAD

**Issue by hjheins** [mohamed-badaoui/asus-touchpad-numpad-driver#9]
As you are already taking the input from the touchpad and enhancing it, with that you made the numerical keypad "key" available. Would it be possible to also make the left top available as key?
-> If you could make the event available as a keypress (like F30), the user could use this as a shortcut to start any desktop application.  (and not just the calculator as asus made available under Windows).

Thanks.

**Comment by mohamed-badaoui** [comment]
Many thanks to @brotzeller for his work on this feature :)
