### ISSUE TITLE
Brightness problems on Asus UP5401EA-OLED024T, type keyboard 2 (m433ia)

### ISSUE THREAD

**Issue by ldrahnik** [mohamed-badaoui/asus-touchpad-numpad-driver#96]
~~When is activated numpad (right top), backlight seems disabled at all. So in fork i changed rows to get full brightness level when is numpad activated and i am trying to figure out what happens. This version of Zenbook has only 1 level of backlight? Or uses another way how is signal encoded and that is reason why it does not works? I tried ```test_brightness.py```, devices found but backlight during sending signals has not been changed.~~

Asus UP5401EA-OLED024T has no levels of backlight. Has only enabled backglight / disabled backlight.

Looks like model type / layout specific variable.

**Comment by Tobiaqs** [comment]
@ldrahnik You could try my fork and see issue #102 . I have a very similar device and also backlight didn't dim at first, but works like a charm now.
