### ISSUE TITLE
Can't use touchpad while numpad is active

### ISSUE THREAD

**Issue by mitakvd** [mohamed-badaoui/asus-touchpad-numpad-driver#97]
I have fully worked Numpad on my Asus UX325EA but I can't use the touchpad while Numpad is active. Is it possible or not?

**Comment by mohamed-badaoui** [comment]
Nope. Even on Windows OS, either the touchpad mode or the numpad mode is activated. Never both at same time.

**Comment by mitakvd** [comment]
Do you sure? I can use the touchpad while Numpad is activated.

**Comment by autodistries** [comment]
So can I on Windows !
